package cn.iocoder.yudao.module.lghjft.controller.admin.xejf.xebftz.vo;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.math.BigDecimal;

@Schema(description = "管理后台 - 小额缴费拨付台账新增/修改 Request VO")
@Data
public class XebfSaveReqVO {
    private Long ghjfId;
    private BigDecimal sfbje;
    private String fbbj;
    private String fbrq;
    private String zjxcrq;
    private String hkpch;
    private String hkpzh;
    private String bz;
    private String spuuid;
    private String rkrq;
    private String jsrq;
    private String jfqj;
    private String skssqq;
    private String skssqz;
    private String zspmDm;
    private BigDecimal gzze;
    private BigDecimal jmse;
    private BigDecimal yfbje;
    private BigDecimal ybtse;
    private String[] jsbj;
    private String deptId;
    private String djxh;
    private String shxydm;
    private String nsrmc;
    private String[] xelx25;
    private String[] xelx24;
    private String[] xelx23;
    private String xwlx;
    private String djzclxmc;
    private BigDecimal jcghbl;
    private BigDecimal jcghje;
    private String jcghhh;
    private String jcghzh;
    private String jcghhm;
    private BigDecimal cbjbl;
    private BigDecimal cbjje;
    private String cbjzh;
    private String cbjhm;
    private String cbjhh;
    private BigDecimal xjghbl;
    private BigDecimal xjghje;
    private String xjghzh;
    private String xjghhm;
    private String xjghhh;
    private BigDecimal sjghbl;
    private BigDecimal sjghje;
    private String sjghzh;
    private String sjghhm;
    private String sjghhh;
    private BigDecimal hyghbl;
    private BigDecimal hyghje;
    private String hyghzh;
    private String hyghhm;
    private String hyghhh;
    private BigDecimal sdghbl;
    private BigDecimal sdghje;
    private String sdghzh;
    private String sdghhm;
    private String sdghhh;
    private BigDecimal szghbl;
    private BigDecimal szghje;
    private String szghzh;
    private String szghhm;
    private String szghhh;
    private BigDecimal qgghbl;
    private BigDecimal qgghje;
    private String qgghzh;
    private String qgghhm;
    private String qgghhh;
}
